doctrine/coding-standard

- Docs/README.md
Removed note about "else if" since it is already part of PSR-2.
> Removed note about "else if"

- README.md
> Update README with newer rules

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
As of PHP 5.3, function invocation in namespaced code is two-step operation. First, function is looked up in current namespace, if not found the _fallback_ mode looks up the function in global scope. This effectively means that global function calls from namespaced code are slower and additionally kill further optimizations and/or inlining into special opcodes, done for [some core functions](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-328810072). Granted, OPcache likely [optimizes the two-step function lookups](https://github.com/php/php-src/blob/php-7.2.0/ext/opcache/Optimizer/optimize_func_calls.c#L150) and [further optimizes some other functions](https://github.com/php/php-src/blob/php-7.2.0/ext/opcache/Optimizer/pass1_5.c#L407), but won't make them compile …
> [RFC] Reference global functions and constants via `use`

- .travis.yml
- tests/expected_report.txt
- tests/fixed/example-class.php
- tests/input/example-class.php
Test for #15.
+ One unrelated test change to test spacing after `!`.
> Added tests for referencing functions and consts in `use`

- README.md
Since we released `2.0.0` of this library, we started adding more rules in `2.1.0`.
This led to consumers of the library to lock onto `~2.1.0` rather than `^2.1.0`.
Effectively, this means that our consumers (library authors) consider our minor
releases to be major releases (and rightfully so!).
This patch suggests to use major versions for any addition to the ruleset that may
lead to code change requirements downstream in consumers, and makes this package
"less special" among the dependencies of any project relying on it.
> Propose semantic versioning of the library

- README.md
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/new_with_parentheses.php
- tests/input/new_with_parentheses.php
Something to start with: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/src/Fixer/Operator/NewWithBracesFixer.php
Already proposed and voted in https://github.com/doctrine/coding-standard/pull/9#issuecomment-353872306
> New with parentheses

- README.md
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/EarlyReturn.php
- tests/input/EarlyReturn.php
Based on https://github.com/doctrine/doctrine2/pull/6929, https://github.com/doctrine/mongodb-odm/pull/1691, https://github.com/doctrine/doctrine2/pull/6889 and https://github.com/doctrine/dbal/pull/2937
> Early return sniff

- lib/Doctrine/ruleset.xml
There are some annotations in https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#7-tags that we some a few occurrences in our repos, but as minimal, I want to vote to forbidden them in our CS :smile:
> [RFC] Add more forbiddenAnnotations

- lib/Doctrine/ruleset.xml
The annotation is used in PHPUnit tests to mark tests without assertions as "not risky".
Note: `dev-master` currently contains changes that would constitute a BC break. I'd like to tag this as either 3.0.1 or 3.1.0 since I believe we should accumulate more changes before tagging 4.0.0. Opinions?
> Allow using doesNotPerformAssertions annotations

- composer.json
- lib/Doctrine/ruleset.xml
Ref: https://github.com/slevomat/coding-standard/pull/284
Found 10 cases of `integer` cases in ORM, 13 cases of `boolean` in DBAL and 20 cases of `boolean` and 17 of `integer` in mongodb-odm
> [RFC] Add SlevomatCodingStandard.PHP.TypeCast

- README.md
- composer.json
- lib/Doctrine/ruleset.xml
You always know an exception is an exception when catching it or
throwing it, so the Exception suffix is useless, but hard to avoid when
you need to group exceptions together, which is why it should be present
in abstract exception names.
See http://mnapoli.fr/approaching-coding-style-rationally/#the-exception-suffix
This is the first of a series of goals I want to clarify regarding exceptions in Doctrine before trying to make a BC version of https://github.com/doctrine/doctrine2/pull/6743
At the moment, things are of course absolutely not like that, but I think that those rules could apply to newly-created exceptions.
> Add rules about exception types naming

- composer.json
- lib/Doctrine/ruleset.xml
Fix for squizlabs/PHP_CodeSniffer#1909 breaking ORM + bumping version.
> Bump PHPCS, fix BC break

- README.md
This is not enforced yet, and might never be, cc @kukulich
> Remove checkmark on unenforceable rule

- lib/Doctrine/ruleset.xml
There is also counerpart sniff: DisallowOneLinePropertyDocComment.
I personally prefer the one-line variant, so starting with that one here.
ORM currently has lots of multilines for single undocumented `@var`.
> Enable RequireOneLinePropertyDocComment sniff

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
Following https://github.com/doctrine/coding-standard/pull/15#issuecomment-363038936 I propose to also disallow fully qualified global class references for consistency.
> [RFC] Reference global classes via `use`

- README.md
Last tagged version is 4.0 but read asks to install 3.0
> Remove constraint version

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/forbidden-functions.php
- tests/input/forbidden-functions.php
I'd like to propose the forbidden usage of the `settype` function. cast should be used instead:
```diff
<?php
$foo = '1';
-settype($foo, 'int');
+$foo = (int) $foo;
var_dump($foo); // int(1)
```
> Forbidden usage of settype function

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/forbidden-functions.php
- tests/input/forbidden-functions.php
I'd like to propose the forbidden usage of the `extract` function. `list` should be used instead.
Some reasons are:
- PHPStan does not recognize the extracted variables
- Sometimes we don't want to whole `array`'s indexes, just some of them
- Control of the extract variables names and values
When #39 gets merged, and this one gets approved, `list` will turn into `[]` :+1: 
```diff
<?php
$bar = [
'foo' => 1,
'bar' => 2,
'baz' => 3,
];
-extract($bar);
+list($fooValue, $barValue, $bazValue) = $bar;
```
> Forbidden usage of extract

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/forbidden-functions.php
- tests/input/forbidden-functions.php
As suggested by @Ocramius in #48 :)
A reason pointed by @morozov is that it initializes unknown/unpredictable variables in the local scope.
A simple array should be used instead:
```diff
<?php
$foo = [
'bar' => 1,
];
-return compact('foo');
+return [
+    'foo' => $foo['bar'],
+];
```
> Forbidden usage of compact

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/namespaces-spacing.php
- tests/input/namespaces-spacing.php
https://github.com/slevomat/coding-standard/commit/e5e3a25327abf80afad3bf8b34218dfcbd079140
In Slevomat CS since 4.5.0, but completely missed (wasn't in release notes).
* One empty line before `use`s.
* No empty lines between different use types.
* One empty line after `use`s.
> Enable UseSpacing sniff

- README.md
We mentioned that a few lines down with a sniff implemented :+1:
> Remove early return duplicated entry

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/new_with_parentheses.php
- tests/fixed/semicolon_spacing.php
- tests/input/semicolon_spacing.php
Suggested by @guilhermeblanco based on [`zendframework/zend-coding-standard#1`](https://github.com/zendframework/zend-coding-standard/pull/1/files#diff-49f27c5b13316b47ac7d0beffaf73ab3R75).
> Use SemicolonSpacing Sniff

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
Simply one empty line before and one after `namespace`.
_Waiting for Slevomat CS 4.6, should be released soon._
> Enable NamespaceSpacing sniff

- lib/Doctrine/ruleset.xml
The previous description gave us the idea that `list` was a forbidden function/struct :)
> Improve short list syntax rule description

- lib/Doctrine/ruleset.xml
This is already part of [PSR-1](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR1/ruleset.xml#L10).
> Remove duplicated ShortOpenTags

- README.md
- docs/en/index.rst
- docs/en/reference/index.rst
- docs/en/sidebar.rst
Related to https://github.com/doctrine/doctrine-website/pull/176
Should I change the README.md to look like the other projects and just point to the docs with a few links? That way we don't have to maintain 2 sets of the same information about the project.
> Add some docs to the doctrine/coding-standard project.

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/input/example-class.php
A declared variable that is return right after it, should be inline:
```diff
function foo() {
-    $foo = 'bar';
-    
-    return $foo;
+    return 'bar';
}
```
> Add Sniff to report useless variables

- .gitattributes
- .github/CODEOWNERS
https://blog.github.com/2017-07-06-introducing-code-owners/
https://help.github.com/articles/about-codeowners/
This should make it easier to handle future PRs - reviews will be requested automatically from the @doctrine/coding-standard-approvers team without the need to specify ~10+ people manually every time.
Minimum approvals needed doesn't change. We may additionally enable _Require reviews from Code Owners_.
WDYT?
> Require reviews from code owners for CS changes

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/class-references.php
- tests/input/class-references.php
The following function calls (or legacy constant) are replaced by their respective constant equivalents:
* `__CLASS__` becomes `self::class`
* `get_parent_class()` becomes parent::class
* `get_called_class()` becomes static::class
* `get_class()` becomes self::class
* `get_class($this)` becomes static::class
There are some issues fixed in Slevomat CS 4.7.1-4.7.2, one more edge case will be fixed in 4.7.3.
Should be ok to land already.
> Enable ModernClassNameReference sniff

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/traits-uses.php
- tests/input/traits-uses.php
Two sniffs for `trait` spacing.
We may not use traits directly (now), but our consumers do and having rules for them is essential part of the CS.
> Enable TraitUseDeclarationSniff & TraitUseSpacingSniff

- .travis.yml
- lib/Doctrine/ruleset.xml
Validate against XML Schema on CI.
`type="boolean"` has apparently no effect:
https://github.com/squizlabs/PHP_CodeSniffer/blob/3.1.1/src/Ruleset.php#L925-L982
and type conversion is done by magic instead: https://github.com/squizlabs/PHP_CodeSniffer/blob/3.1.1/src/Ruleset.php#L1232-L1253
> Validate ruleset against XML schema

- docs/en/reference/customizing.rst
- docs/en/reference/index.rst
- docs/en/sidebar.rst
* document `phpcs.xml(.dist)?`
* document how to customize ruleset
@jwage Can you please proofread this? Thanks.
> Document how to customize rules

- .travis.yml
- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/doc-comment-spacing.php
- tests/input/doc-comment-spacing.php
Sniff to require a newline between between description and tags, a newline between annotation groups and no newline before/after phpDoc content.
Example:
```php
/**
* Description
* More Description
*
* @internal
* @deprecated
*
* @link https://example.com
* @see  other
* @uses other
*
* @ORM\Id
* @ORM\Column
* @ODM\Id
* @ODM\Column
*
* @param int[] $foo
* @param int[] $bar
*
* @return int[]
*
* @throws FooException
* @throws BarException
*/
public function d(iterable $foo, iterable $bar) : iterable
{
}
```
This is based on spacing/format used in ORM, does this properly fit other projects (i.e. ODM) too?
Changes in ORM with this enabled are mostly (superfluous newlines) cosmetical: https://github.com/Majkl578/doctrine-orm/commit/68920f1cf50609221fee3f7260cb65b1b2cfc300
> phpDoc annotation spacing

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/optimized-functions.php
- tests/input/optimized-functions.php
From readme:
> PHP optimizes some internal functions into special opcodes on VM level. Such optimization results in much faster execution compared to calling standard function. This only works when these functions are not invoked with argument unpacking (...).
>
> The list of these functions varies across PHP versions, but is the same as functions that must be referenced by their global name (either by \ prefix or using use function), not a fallback name inside namespaced code.
> Enable OptimizedFunctionsWithoutUnpacking sniff

- composer.json
- lib/Doctrine/ruleset.xml
As described in [the upgrade guide of PHPCS v3.3.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0#Deprecations), there's a new array syntax in favor of the old one that was deprecated and will be removed in v4. Here's an example:
```diff
-<property name="forbiddenFunctions" type="array" value="sizeof=>count,delete=>unset,print=>echo,is_null=>null,create_function=>null"/>
+<property name="forbiddenFunctions" type="array">
+    <element key="sizeof" value="count"/>
+    <element key="delete" value="unset"/>
+    <element key="print" value="echo"/>
+    <element key="is_null" value="null"/>
+    <element key="create_function" value="null"/>
+</property>
```
> Use new PHPCS array syntax

- composer.json
Dealerdirect/phpcodesniffer-composer-installer version [0.5.0](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.5.0) has been released which contains (among others) a fix for the plugin breaking the composer lifecycle.
> Update the DealerDirect's composer installer dependency to v0.5.0

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/input/forbidden-comments.php
`Class Foo` doesn't really add anything of worth to a class doc block, thus should be disallowed in the same fashion as getters/setters and constructors. I believe this is the default template for PhpStorm.
> Disallow "Class <name>" as class comment

- lib/Doctrine/ruleset.xml
- tests/fixed/example-class.php
- tests/input/example-class.php
I suggest allowing descriptions for `@throws` to be started with a non-capital letter as it is more natural to compose a complete sentence out of the line like:
```
@throws RuntimeException if the file could not be written.
```
As a further improvement one might even enforce sentences like this (starting with `if`).
What do you guys think?
> Exclude Squiz.Commenting.FunctionComment.ThrowsNotCapital sniff

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/trailing_comma_on_array.php
- tests/input/trailing_comma_on_array.php
For some weird reason travis didn't run on https://github.com/doctrine/coding-standard/pull/102, reopening it then...
> Add failing test to reproduce bug with associative arrays

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/duplicate-assignment-variable.php
- tests/input/duplicate-assignment-variable.php
One of the sniffs that came up with Slevomat/CS v4.8.0 and we didn't add.
**This sniff is not autofixable**.
> Forbid duplicated variables assignments

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/EarlyReturn.php
- tests/fixed/UselessConditions.php
- tests/input/UselessConditions.php
This PR adds a Sniff to automate a couple of refactoring I've been doing across Doctrine's repositories.
Note that this PR will affect structs that have early returns, as tested under the method `unecessaryIfMethodForEarlyReturn`.
> Add rule to force simplification of returns

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/test-case.php
- tests/fixed/trailing_comma_on_array.php
- tests/input/trailing_comma_on_array.php
Backporting these:
- https://github.com/doctrine/coding-standard/pull/91
- https://github.com/doctrine/coding-standard/pull/93
- https://github.com/doctrine/coding-standard/pull/103
I'm considering the dependency upgrade as a fix here since composer commands sometimes were failing and seems to be solved.
> Apply fixes on 5.x

- lib/Doctrine/ruleset.xml
Slevomat CS 5.0 drops `usefulAnnotations` so we are forced to switch to `allAnnotationsAreUseful` instead.
From now on there is no whitelist for useful annotations, only the blacklist provided by ForbiddenAnnotations.
Sadly I'm still not convinced this is a good step forward though.
> Make all annotations useful by default

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/UselessConditions.php
This only moves us to Slevomat CS 5.0 - no sniffs are added, changed or removed.
New sniffs and changes coming in upcoming PRs.
> Upgrade to Slevomat CS 5.0

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/spread-operator.php
- tests/input/spread-operator.php
Simple sniff to check that ellipsis are not followed by spacing - see tests.
> Enable SpreadOperatorSpacing sniff

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/constants-no-lsb.php
- tests/input/constants-no-lsb.php
Constants are not meant to be overriden, using such behaviour asks for troubles and abstract method should be used instead.
> Forbid LSB for constants

- .travis.yml
Not sure why do you ignore my comment at https://github.com/doctrine/coding-standard/pull/100#issuecomment-449727531, hopefully you will listen to CI.
> Trigger CI failure when phpcbf cannot fix the file

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/inline_type_hint_assertions.php
- tests/input/inline_type_hint_assertions.php
This RFC proposes replacing the typical `/** @var Something $something */` with `assert($something instanceof Something)` wherever possible.
This has a few nice side-effects that @dasprid exposed:
1. the type declaration is no longer a comment, but AST nodes that can be inspected and have well defined meaning in the language itself
2. `assert()` can report when these assumptions fail (once the CS rule is applied to a codebase)
3. `assert()` can be turned off, making this an informational addition
I didn't dig into PHPStan's new type declarations, which support `foo[]`, `(foo|bar)[]` and union types (`foo&bar`) too much, so this is just a first sketch of the idea I stole from @dasprid.
> Replace inline docblock declarations with assertions

- .travis.yml
- composer.json
Build doesn't run anymore on 7.1
>   Problem 1
- Installation request for slevomat/coding-standard dev-master#63a8186b129ee96d1277e68c80cf87c8cdb356d1 -> satisfiable by slevomat/coding-standard[dev-master].
- slevomat/coding-standard dev-master requires php ^7.2 -> your PHP version (7.1.27) does not satisfy that requirement.
> Drop PHP 7.1, add 7.4 to Travis

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/NamingCamelCase.php
- tests/input/NamingCamelCase.php
I noticed there was no sniff enabled to force camelCase variable names. 
I cannot create issue to ask so I created this PR. Is there a reason for absence of such rule or is this PR actually viable? Eg. methodNames() or ClassNames are required to be camelCased.
> Camel case vars

- composer.json
To fix the PHP 7.4 compatibility issues.
This shall be solved as soon as they release v3.5.0.
> Lock PHPCS in its latest commit

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
- tests/fixed/namespaces-spacing.php
- tests/fixed/use-ordering.php
- tests/input/namespaces-spacing.php
- tests/input/use-ordering.php
[PSR-12 is accepted](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide.md) so I was thinking it's time to default to it and to defaults in Jetbrains' IDEs. WDYT?
> Drop psr12Compatible false, default is true

- composer.json
- lib/Doctrine/ruleset.xml
The only sniff that affects us is `Squiz.Functions.FunctionDeclarationArgumentSpacing`, that now checks space after a variadic operator. But, since we have `SlevomatCodingStandard.Operators.SpreadOperatorSpacing` doing that on a larger scale, we can ignore that one. Changelog:
> - `Squiz.Functions.FunctionDeclarationArgumentSpacing` now checks for no space after a variadic operator
- If you don't want this new behaviour, exclude the `SpacingAfterVariadic` error message in a `ruleset.xml` file
This PR will allow us to adopt PSR-12 in the future.
> Update to PHPCS v3.5.x

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
- tests/input/example-class.php
_built on top of https://github.com/doctrine/coding-standard/pull/135_
We require space before `return`, let's require it also before `yield`, `yield from` and `throw`
> Require space before throw, yield and yield from

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
The workshop in slevomat/coding-standard ignited its furnaces after a while so I though it's time to bump its version a bit forward.
Notable BC break to mind there is https://github.com/slevomat/coding-standard/commit/ea725d3036a203a0939a38cfc7a1826c88c8eabb
> Bump slevomat cs

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
- tests/input/example-class.php
_based on top of https://github.com/doctrine/coding-standard/pull/136_
Addresses https://github.com/doctrine/coding-standard/pull/135#pullrequestreview-322967213
> Require space after Block Control Structures

- .travis.yml
- Makefile
- bin/test.sh
- composer.json
- docs/en/reference/index.rst
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/example-class.php
- tests/fixed/type-hints.php
- tests/input/example-class.php
- tests/input/type-hints.php
- tests/php-compatibility.patch
This aggregates:
- https://github.com/doctrine/coding-standard/pull/142
- https://github.com/doctrine/coding-standard/pull/139
- https://github.com/doctrine/coding-standard/pull/138
Things to note:
- There are few `traversableTypehints` listed for type hints related sniffs. Originally, there was only Doctrine Collection.
-  Spaces are not required before block control structures now, it's status quo. It's possible to enforce it by disabling excludes for `BlockControlStructureSpacing` sniff if desired.
> Upgrade slevomat/coding-standard to v6

- composer.json
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/ControlStructures.php
- tests/fixed/binary_operators.php
- tests/fixed/concatenation_spacing.php
- tests/fixed/trailing_comma_on_array.php
- tests/input/ControlStructures.php
- tests/input/binary_operators.php
- tests/input/trailing_comma_on_array.php
- tests/php-compatibility.patch
This PR proposes that the Doctrine's CS adopts [PSR-12](https://www.php-fig.org/psr/psr-12/) as the base for our standards, with a few changes, [as voted in the past](https://github.com/doctrine/coding-standard/pull/9).
Important changes:
- `SlevomatCodingStandard.ControlStructures.NewWithParentheses` was dropped in favor of `PSR12.Classes.ClassInstantiation`, in specific `PSR12.Classes.ClassInstantiation.MissingParentheses`
- The `tests/fixed/binary_operators.php` was added to ensure the behaviour of a new rule: `PSR12.Operators.OperatorSpacing` (will close #123, #126 as well #134 if approved)
> Adopt PSR-12 as base coding standard

- composer.json
- lib/Doctrine/ruleset.xml
- tests/fixed/negation-operator.php
- tests/input/negation-operator.php
- tests/php-compatibility.patch
The new [`slevomat/coding-standard` version 6.1](https://github.com/slevomat/coding-standard/releases/tag/6.1.0) contains some news sniffs. 
With this, and following PRs, I'd like to suggest some of them.
> Use `NegationOperatorSpacingSniff` to ensure no space before `-`

- lib/Doctrine/ruleset.xml
- tests/fixed/single-line-array-spacing.php
- tests/input/single-line-array-spacing.php
- tests/php-compatibility.patch
See https://github.com/slevomat/coding-standard/#slevomatcodingstandardarrayssinglelinearraywhitespace-.
> Use `SingleLineArrayWhitespace` to ensure single line arrays spacing

- Makefile
Previously, the `make test-fix` outputed something like:
```sh
diff tests/input2/array_indentation.php tests/fixed/array_indentation.php
14c14
< $multiArray = [
---
> $multiArray =[
Only in tests/fixed: single-line-array-spacing.php~
make: *** [test-fix] Error 1
```
Now, using `diff -u`, we have a Git like diff, much easier to understand:
```sh
diff -u tests/input2/array_indentation.php tests/fixed/array_indentation.php
--- tests/input2/array_indentation.php	2020-02-04 22:19:28.000000000 -0300
+++ tests/fixed/array_indentation.php	2020-02-04 22:16:04.000000000 -0300
@@ -11,7 +11,7 @@
5,
];
-$multiArray = [
+$multiArray =[
'0' => [
'2' => 2,
1 => '1',
Only in tests/fixed: single-line-array-spacing.php~
make: *** [test-fix] Error 1
```
> Improve diff while running `test-fix`

- .docker/validate-against-schema/Dockerfile
- .gitattributes
- .github/workflows/continuous-integration.yml
- README.md
This PR
💁‍♂ Not sure if this matches the expectations - I have tried to create a workflow with jobs equivalent to the stages currently used on Travis CI. Note that the actions will not be triggered here as I do not have push privileges (that's why I'm still leaving the Travis CI integration as it is).
> Enhancement: Add workflow for GitHub Actions

- lib/Doctrine/ruleset.xml
- 'Forbid' always take captifal 'F', same for 'Report';
- Suffix 'Trait' is forbidden for traits, not interfaces.
> Normalize documentation comments

- lib/Doctrine/ruleset.xml
- tests/fixed/forbidden-comments.php
- tests/input/forbidden-comments.php
- tests/php-compatibility.patch
Tools like PHPStorm also generate these kinda comments. (And we had a code base filled to the brim with them)
I'd love to add tests for this, but i couldn't get the test suite to work locally.
> Remove usless interface and trait comments

- .dependabot/config.yml
- composer.json
Dependabot (https://dependabot.com) is a bot that will help us keep our
dependencies up to date.
This initial configure will open PRs during workdays and working hours (defined in
https://app.dependabot.com) for our PHP Composer dependencies.
No automerge will be performed for now by Dependabot.
> Introduce Dependabot

- .github/workflows/continuous-integration.yml
Since we still don't support PHP 8 and we can't `allow-failures` on that, let's remove it.
> Remove PHP 8 from GitHub Actions

- lib/Doctrine/ruleset.xml
- tests/fixed/ControlStructures.php
- tests/fixed/example-class.php
- tests/fixed/namespaces-spacing.php
- tests/fixed/use-ordering.php
- tests/input/ControlStructures.php
- tests/input/example-class.php
- tests/input/namespaces-spacing.php
- tests/input/use-ordering.php
[PSR-12](https://www.php-fig.org/psr/psr-12) is an extension of the PSR-2 set of rules
that aims to standardize the code style.
As per PSR-12, under the [item 3](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements):
> The header of a PHP file may consist of a number of different blocks. If present,
> each of the blocks below MUST be separated by a single blank line, and MUST NOT
> contain a blank line. Each block MUST be in the order listed below, although
> blocks that are not relevant may be omitted.
For context on why this was voted in the past, see #9.
> Adopt PSR-12 for imports statements separation

- lib/Doctrine/ruleset.xml
- tests/fixed/PropertyTypeHintSpacing.php
- tests/input/PropertyTypeHintSpacing.php
- tests/php-compatibility.patch
This new rule checks for things like:
- one space between the typehint and the property name
- one space between the typehint and the property's modifiers
- no space between the nullability symbol and the typehint
This rule does not check for:
- How many lines the typed properties are separated by
- If two consecutive properties have default values, the `=` sign will be aligned
This also falls under the PSR-12, by [the item 4.3](https://www.php-fig.org/psr/psr-12/#43-properties-and-constants):
> There MUST be a space between type declaration and property name.
> Ensure that Typed Properties are spaced correctly

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/null_coalesce_equal_operator.php
- tests/input/null_coalesce_equal_operator.php
- tests/php-compatibility.patch
This is a new rule that will only affect PHP 7.4+ codebases :)
> Introduce rule requiring Null Coalesce Equal Operator

- lib/Doctrine/ruleset.xml
- tests/fixed/ControlStructures.php
- tests/input/ControlStructures.php
- tests/php-compatibility.patch
As reported via slevomat/coding-standard#867, in case that a switch
with cases returning or breaking, the `JumpStatementsSpacing` sniff
wasn't handling it properly.
These 3 new options ensure that this sniff handles this case as well.
Requested by @morozov via https://github.com/doctrine/coding-standard/pull/167#issuecomment-606056629.
> Ensure that spacing around `cases` are consistent

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/constants-var.php
- tests/input/constants-var.php
- tests/php-compatibility.patch
Although PSR only have this rule suggested to class properties, we
enforce it for constants as well.
> Add rule forbidding more than one constant declared per statement

- .travis.yml
Warnings from https://travis-ci.org/github/doctrine/coding-standard/builds/676955885/config:
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing os, using the default linux
```
> Fix warnings on Travis CI configuration file

- composer.json
Not sure why this is in here, looks like an old relic that was forgotten to remove. Also causes issue with `roave/better-reflection` when using the `MakeLocatorForComposerJsonAndInstalledJson` locator factory that assumes any defines autoload paths to exist.
Mutually exclusive with: #177
> Remove dead sniffs autoload

- .doctrine-project.json
Noticed that on https://doctrine-project.org/projects/coding-standard.html.
> Fix documentation version numbers and labels

- .github/workflows/continuous-integration.yml
using the recommended style of depdency declaration promoted by the Github Action author.
also getting a current php8 version with it.
> update to latest shivammathur/setup-php Github Action

- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/fixed/arrow-functions-format.php
- tests/input/arrow-functions-format.php
- tests/php-compatibility.patch
This new rule enforces format for already declared `arrow functions` (this sniff
does not convert anonymous function to arrow functions).
-------
Note for reviewers: the idea of having `1 space` set for `spacesCountAfterKeyword` is that we follow the current standards for function calls.
Pool on Twitter for reference: https://twitter.com/carusogabriel/status/1251576089497010177
> Add rule to ensure Arrow Functions declaration format

- composer.json
- tests/expected_report.txt
- tests/fixed/ControlStructures.php
- tests/php-compatibility.patch
`slevomat/coding-standard` has fixed one bug that we need to reflect on our tests.
After this and #192, we should be ready to release the [`v8`](https://github.com/doctrine/coding-standard/milestone/11).
> Update tests expectations based on bugfix in dependencies

- .github/workflows/continuous-integration.yml
Composer v2.0.0-alpha1 was released today, this will prevent upgrading
to it by mistake.
See https://github.com/shivammathur/setup-php/issues/229
> Update to v2 of the action

- Makefile
- composer.json
- docs/en/reference/customizing.rst
- docs/en/reference/index.rst
- lib/Doctrine/ruleset.xml
- tests/expected_report.txt
- tests/php-compatibility.patch
Release [8.1.0](https://github.com/doctrine/coding-standard/milestone/15)
8.1.0
=====
- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**
- [213: Composer: update PHPCS Composer plugin dependency](https://github.com/doctrine/coding-standard/pull/213) thanks to @jrfnl
> Merge release 8.1.0 into master

- .github/workflows/continuous-integration.yml
- composer.json
Restricting the 8.1 branch to 7.1 is an artificial constraint, the code works on 7.1 just fine.
https://github.com/doctrine/coding-standard/pull/127 removed 7.1 support, but slevomat/coding-standard reintroduced 7.1 support with https://github.com/slevomat/coding-standard/commit/b26cb5cb3a0ae2b64a174b9cc98cab70c92e2f8e#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34
> Still works on PHP 7.1
